//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        public int HabitacionId { get; set; }
        public string Titulo { get; set; }
        public string URLImagen { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> NCamas { get; set; }
        public Nullable<bool> TV { get; set; }
        public Nullable<bool> SanitarioPrivado { get; set; }
        public Nullable<bool> AC { get; set; }
    }
}
