//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservacion
    {
        public int ReservacionId { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> HabitacionId { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> ClienteId { get; set; }
    }
}
